/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeakerSpeakerIdRouteImport } from './routes/speaker.$speakerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakerSpeakerIdRoute = SpeakerSpeakerIdRouteImport.update({
  id: '/speaker/$speakerId',
  path: '/speaker/$speakerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/speaker/$speakerId': typeof SpeakerSpeakerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/speaker/$speakerId': typeof SpeakerSpeakerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/speaker/$speakerId': typeof SpeakerSpeakerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/speaker/$speakerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/speaker/$speakerId'
  id: '__root__' | '/' | '/speaker/$speakerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpeakerSpeakerIdRoute: typeof SpeakerSpeakerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaker/$speakerId': {
      id: '/speaker/$speakerId'
      path: '/speaker/$speakerId'
      fullPath: '/speaker/$speakerId'
      preLoaderRoute: typeof SpeakerSpeakerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpeakerSpeakerIdRoute: SpeakerSpeakerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
